#!/usr/bin/env bash
#
# generate_moc.sh — regenerates the knowledge store's GENERATED navigation
# MOCs (temperloop#231, epic #226 "generated navigation"):
#
#   Index.md                    — top-level index of every detected project
#   Projects/<name>/Home.md     — one per detected project, listing every
#                                 note associated with that project
#
# Detection: a note belongs to project <name> when EITHER its filename
# matches the `<name> - <title>.md` convention (the filename rule from
# claude/CLAUDE.md § Decision capture, applied uniformly across Decisions/,
# Patterns/, Mistakes/, Context/) OR its YAML frontmatter carries a
# `project/<name>` tag. The union of both signals is the project's note set.
# <name> must contain no space — this deliberately excludes the unrelated
# `<date> <project> - <title>.md` Plans/ convention, whose "prefix" (date +
# project) is not a bare project slug.
#
# GENERATED, NEVER HAND-CURATED (epic #226 ADR §2.1: project-first browsing
# is served VIRTUALLY by generation, never hand-curation). Every file this
# script writes carries a do-not-hand-edit banner as its first line. Before
# overwriting a target, the script checks for that banner: if the target
# already exists WITHOUT it (hand-authored content, or content that pre-dates
# this generator), the script REFUSES to overwrite it and instead reports a
# conflict — the same propose/dispose style as vault_hygiene_report.sh
# (report now; /tidy appends a `--format entry` conflict block to a pipeline
# surface for check-in to dispose). Nothing generation collides with is ever
# silently destroyed.
#
# Usage:
#   generate_moc.sh [--root DIR] [--format entry]
#     --root DIR       knowledge-store root (default: the knowledge_store
#                      seam's ks_root — KNOWLEDGE_STORE_ROOT if set, else
#                      its generic per-user default; see knowledge_store.sh)
#     --format entry   print a ready-to-append `### … Status: open` block
#                      IFF a hand-authored conflict was found (nothing when
#                      clean); default prints a human-readable report.
#
# No-op (exit 0, no writes) when:
#   - the store root is absent (a stranger's bare kernel checkout has no
#     vault at all), or
#   - zero projects are detected (no filename-prefix or `project/<name>`-tag
#     signal anywhere in the store — including a root that exists but is
#     empty).
# Both are "nothing to generate yet" — neither Index.md nor any
# Projects/<name>/Home.md is created in either case.
#
# Idempotent: two runs against an unchanged store produce byte-identical
# generated files — no timestamp or run-specific data is embedded in
# generated content (only the entry-format conflict report, never written
# into a generated MOC, carries a timestamp).
#
# Kept POSIX-bash-3.2 compatible (no mapfile/associative arrays), matching
# the sibling drain/ scripts, so it runs on the macOS dev shell as well as
# Linux CI.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=workflows/scripts/lib/knowledge_store.sh
. "$HERE/../lib/knowledge_store.sh"

BANNER='<!-- GENERATED FILE — DO NOT EDIT BY HAND. Regenerated by /tidy via workflows/scripts/drain/generate_moc.sh; hand edits will not be overwritten (generation instead skips this file and reports a conflict) but will also never be reflected in the generated content. -->'

# ── Arg parse ─────────────────────────────────────────────────────────────────
ROOT="$(ks_root)"
FORMAT="report"
while [ $# -gt 0 ]; do
  case "$1" in
    --root)   ROOT="${2:-}"; shift 2 ;;
    --root=*) ROOT="${1#--root=}"; shift ;;
    --format) FORMAT="${2:-}"; shift 2 ;;
    --format=*) FORMAT="${1#--format=}"; shift ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
case "$FORMAT" in report|entry) ;; *) echo "unknown --format: $FORMAT (report|entry)" >&2; exit 2 ;; esac

# Route every knowledge_store call (ks_root/ks_write below) at the resolved
# root, so --root overrides work for tests without touching the real store.
export KNOWLEDGE_STORE_ROOT="$ROOT"

# ── Root-absent no-op (a stranger's checkout, or a mis-set root) ───────────────
if [ ! -d "$ROOT" ]; then
  [ "$FORMAT" = "entry" ] && exit 0
  echo "generate_moc: root not found ($ROOT) — skipping (no vault in this checkout)"
  exit 0
fi

# ── Enumerate candidate notes (every *.md, minus vault machinery + our own
#    generated output) ─────────────────────────────────────────────────────────
# SC2119: ks_list's [prefix] parameter is genuinely optional (see
# knowledge_store.contract.md) — the zero-arg call means "whole store",
# which is exactly what we want here.
# shellcheck disable=SC2119
all_docs="$(ks_list)"
CANDIDATES=""
while IFS= read -r f; do
  [ -n "$f" ] || continue
  case "$f" in
    .obsidian/*|.smart-env/*|.git/*) continue ;;
    Sessions/_inbox/*) continue ;;   # ephemeral raw stubs, not curated content
    Projects/*) continue ;;          # our own generated output — never a source
    Index.md) continue ;;            # our own generated output — never a source
  esac
  CANDIDATES="${CANDIDATES}${f}"$'\n'
done <<<"$all_docs"

# ── Detect project associations: <project>\t<relpath> pairs ────────────────────
PAIRS=""
while IFS= read -r f; do
  [ -n "$f" ] || continue
  base="${f##*/}"

  # Filename-prefix signal: `<project> - <title>.md`, project = first token,
  # no space allowed in it (excludes the unrelated `<date> <project> -
  # <title>.md` Plans/ convention, whose leading token is a date+space).
  proj=""
  case "$base" in
    *" - "*.md)
      proj="${base%% - *}"
      case "$proj" in *" "*) proj="" ;; esac
      ;;
  esac
  if [ -n "$proj" ]; then
    PAIRS="${PAIRS}${proj}"$'\t'"${f}"$'\n'
  fi

  # Tag signal: a `project/<name>` token anywhere in the YAML frontmatter
  # block (flow-style `tags: [..., project/x]` or block-style `- project/x`).
  tagged="$(awk 'NR==1{ if ($0!="---"){exit} next } /^---$/{exit} {print}' "$ROOT/$f" 2>/dev/null \
    | grep -oE 'project/[A-Za-z0-9_.-]+' 2>/dev/null | sed 's#^project/##' || true)"
  if [ -n "$tagged" ]; then
    while IFS= read -r tp; do
      [ -n "$tp" ] || continue
      case "$tp" in */*|..|.) continue ;; esac   # path-unsafe token, ignore
      PAIRS="${PAIRS}${tp}"$'\t'"${f}"$'\n'
    done <<<"$tagged"
  fi
done <<<"$CANDIDATES"

PAIRS_SORTED="$(printf '%s\n' "$PAIRS" | awk 'NF' | sort -u)"

# ── Zero-project no-op ──────────────────────────────────────────────────────────
if [ -z "$PAIRS_SORTED" ]; then
  [ "$FORMAT" = "entry" ] && exit 0
  echo "generate_moc: no projects detected under $ROOT (no filename-prefix or project/<name> tag) — nothing to generate"
  exit 0
fi

PROJECTS="$(printf '%s\n' "$PAIRS_SORTED" | cut -f1 | sort -u)"

# ── Write helper: refuse to clobber a hand-authored (non-banner) target ────────
# Tracks conflicts (targets skipped because they exist without our banner) and
# writes (targets successfully generated) as newline-delimited lists.
CONFLICTS=""
WRITTEN=""

write_generated() {
  local relpath="$1"
  local content="$2"
  local full first_line
  full="$ROOT/$relpath"
  first_line=""
  if [ -e "$full" ]; then
    first_line="$(head -n1 "$full" 2>/dev/null || true)"
    if [ "$first_line" != "$BANNER" ]; then
      CONFLICTS="${CONFLICTS}${relpath}"$'\n'
      return 0
    fi
  fi
  printf '%s\n' "$content" | ks_write "$relpath"
  WRITTEN="${WRITTEN}${relpath}"$'\n'
}

# ── Build + write one Projects/<name>/Home.md per detected project ─────────────
INDEX_PROJECT_LINES=""
while IFS= read -r proj; do
  [ -n "$proj" ] || continue
  case "$proj" in */*|..|.) continue ;; esac   # path-unsafe project name, skip

  files="$(printf '%s\n' "$PAIRS_SORTED" | awk -F'\t' -v p="$proj" '$1==p{print $2}' | sort -u)"
  count="$(printf '%s\n' "$files" | awk 'NF' | wc -l | tr -d ' ')"
  plural="s"; [ "$count" = "1" ] && plural=""

  body="# ${proj} — Home"$'\n\n'
  body="${body}Notes associated with \`${proj}\` via a \`${proj} - ...\` filename prefix or a \`project/${proj}\` tag. Regenerated by \`/tidy\` — see \`Index.md\`."$'\n\n'
  body="${body}## Notes"$'\n\n'
  while IFS= read -r nf; do
    [ -n "$nf" ] || continue
    body="${body}- [[${nf%.md}]]"$'\n'
  done <<<"$files"

  write_generated "Projects/${proj}/Home.md" "${BANNER}"$'\n\n'"${body}"
  INDEX_PROJECT_LINES="${INDEX_PROJECT_LINES}- [[Projects/${proj}/Home]] (${count} note${plural})"$'\n'
done <<<"$PROJECTS"

# ── Build + write Index.md ──────────────────────────────────────────────────────
index_body="# Index"$'\n\n'
index_body="${index_body}Auto-generated top-level index of detected projects. Regenerated by \`/tidy\` from filename prefixes (\`<project> - ...\`) and \`project/<name>\` tags — never hand-edit; see each project's \`Projects/<name>/Home.md\` for its notes."$'\n\n'
index_body="${index_body}## Projects"$'\n\n'
index_body="${index_body}${INDEX_PROJECT_LINES}"

write_generated "Index.md" "${BANNER}"$'\n\n'"${index_body}"

# ── Emit ──────────────────────────────────────────────────────────────────────
CONFLICTS="$(printf '%s\n' "$CONFLICTS" | awk 'NF')"
WRITTEN="$(printf '%s\n' "$WRITTEN" | awk 'NF')"

if [ "$FORMAT" = "entry" ]; then
  [ -z "$CONFLICTS" ] && exit 0   # no conflicts → append nothing
  ts="$(date '+%Y-%m-%d %H:%M')"
  host="$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo host)"
  printf '### %s · moc generation conflict · %s\n' "$ts" "$host"
  printf -- '- **Decision:** dispose of %d moc-generation conflict(s) below (drain proposed; check-in disposes).\n' \
    "$(printf '%s\n' "$CONFLICTS" | awk 'NF' | wc -l | tr -d ' ')"
  printf -- '- **Findings:**\n'
  printf '%s\n' "$CONFLICTS" | awk 'NF' | sed 's/^/  - hand-authored, not overwritten: /'
  printf -- '- **Status:** open\n'
  exit 0
fi

# Default: human-readable report.
echo "=== generate_moc ($ROOT) ==="
if [ -n "$WRITTEN" ]; then
  printf '%s\n' "$WRITTEN" | awk 'NF' | sed 's/^/  generated: /'
else
  echo "  generated: (nothing — all targets already up to date or skipped)"
fi
if [ -n "$CONFLICTS" ]; then
  printf '%s\n' "$CONFLICTS" | awk 'NF' | sed 's/^/  skipped (hand-authored, not overwritten): /'
fi
echo "---"
if [ -n "$CONFLICTS" ]; then
  echo "CONFLICTS: $(printf '%s\n' "$CONFLICTS" | awk 'NF' | wc -l | tr -d ' ')"
else
  echo "OK"
fi
exit 0
