# foundation-kernel Makefile — standalone subset of foundation's Makefile,
# generated by workflows/scripts/kernel/seed-kernel-repo.sh (F#803). Every
# recipe body here is copied verbatim from foundation's own Makefile for the
# kernel-classified targets scripts/quality-gates.sh's KERNEL_GATES invoke,
# plus the docs generator. Do not hand-edit this file in the kernel repo —
# change the source in foundation's Makefile and re-run the seeder.
SHELL := /bin/bash
FOUNDATION := $(shell pwd)
BOARD_SRC := $(FOUNDATION)/workflows/scripts/board
BUILD_SRC := $(FOUNDATION)/workflows/scripts/build
PROBE_SRC := $(FOUNDATION)/workflows/scripts/probe
DEMO_SRC := $(FOUNDATION)/workflows/scripts/demo
PROPOSAL_SRC := $(FOUNDATION)/workflows/scripts/proposal
BIN_SRC := $(FOUNDATION)/bin
HOOKS_SRC := $(FOUNDATION)/claude/hooks

.PHONY: help shellcheck quality-gates test-board test-board-dual-adapter test-build test-build-workflow \
	test-hooks test-install test-install-links test-install-worktree-guard \
	test-prune-branches validate-live-drain validate-command-run-emit \
	validate-lexicon test-scan-stub lint-pr-body-test test-stranger-config \
	test-kernel-manifest test-kernel-denylist test-kernel-gitleaks test-producer-egress docs \
	test-docs-generator test-conventions-probe test-demo test-proposal-pr guard-install-worktree test-try

help:
	@echo "Targets:"
	@echo "  quality-gates          Run the full static gate set (= CI's checks job)"
	@echo "  shellcheck              Whole-tree shellcheck (production + hook scripts)"
	@echo "  test-board              Board toolkit tests"
	@echo "  test-build              Build deterministic-spine toolkit tests"
	@echo "  test-build-workflow     build-level.mjs offline harness"
	@echo "  test-hooks              Claude Code hook tests"
	@echo "  test-install            install-settings reconcile test"
	@echo "  test-install-links      install-links helper tests"
	@echo "  test-install-worktree-guard  Canonical-checkout guard tests"
	@echo "  test-prune-branches     prune-merged-branches.sh tests"
	@echo "  validate-live-drain     Live/Drain pairing registry lint"
	@echo "  validate-command-run-emit  emit-command-run.sh presence/wiring lint"
	@echo "  validate-lexicon        drain-mind tell-lexicon lint"
	@echo "  test-scan-stub          Session-stub scanner tests"
	@echo "  lint-pr-body-test       PR-body issue-linkage lint tests"
	@echo "  test-stranger-config    Kernel-portability seam integration test"
	@echo "  test-kernel-manifest    kernel-manifest.txt coverage check"
	@echo "  test-kernel-denylist    Personal-token denylist check"
	@echo "  test-kernel-gitleaks    gitleaks secret scan over the kernel set"
	@echo "  test-producer-egress    Egress lint over the Epic E value-loop producers"
	@echo "  docs                    Render the generated docs site"
	@echo "  test-docs-generator     Docs generator unit tests"
	@echo "  test-conventions-probe  Conventions-probe (read-only repo-convention detector) tests"
	@echo "  test-demo               Demo-repo seed script tests"
	@echo "  test-proposal-pr        Proposal-PR generator (tree-diff -> reviewable PR) tests"
	@echo "  test-try                foundation try (zero-config, zero-write taste) tests"

# Canonical-checkout guard (foundation #509): refuses to run from a linked git
# worktree unless FORCE_REHOME=1. Not wired into any target below today (no
# install-* target ships in this standalone Makefile yet) — kept for parity
# with foundation's own Makefile and for a future install-* target to depend
# on without reintroducing the guard logic.
guard-install-worktree:
	@bash -c ' \
		if [ -n "$${FORCE_REHOME:-}" ]; then exit 0; fi; \
		_common="$$(git rev-parse --git-common-dir 2>/dev/null)" || exit 0; \
		_gitdir="$$(git rev-parse --absolute-git-dir 2>/dev/null)" || exit 0; \
		_common_abs="$$(cd "$$_common" && pwd)"; \
		_gitdir_abs="$$(cd "$$_gitdir" && pwd)"; \
		if [ "$$_common_abs" != "$$_gitdir_abs" ]; then \
			_canonical="$$(dirname "$$_common_abs")"; \
			echo "make: refusing to install from a git worktree ($$PWD)." >&2; \
			echo "  Run from the canonical checkout: $$_canonical" >&2; \
			echo "  Set FORCE_REHOME=1 to override." >&2; \
			exit 1; \
		fi \
	'

# test-board runs every tests/test_*.sh via a glob rather than mirroring
# foundation's explicit list — a static copy of that list goes stale the
# moment foundation registers a new board test (F#836: the pre-glob heredoc
# silently skipped test_issues_backend.sh in kernel CI). The glob matches
# whatever tests are actually vendored, so kernel coverage can never trail
# the tree it ships.
test-board:
	@echo "==> Running board toolkit tests..."
	@for t in $(BOARD_SRC)/tests/test_*.sh; do \
		bash "$$t" >/dev/null 2>&1 && echo "  [ok] $$(basename $$t)" || { echo "  [FAIL] $$(basename $$t)"; exit 1; }; \
	done

test-board-dual-adapter:
	@echo "==> Running dual-adapter SAFE-TIER funnel integration suite..."
	@bash $(BOARD_SRC)/tests/test_board_dual_adapter.sh

test-build:
	@echo "==> Running build toolkit tests..."
	@for t in $(BUILD_SRC)/tests/test_*.sh; do \
		bash "$$t" >/dev/null 2>&1 && echo "  [ok] $$(basename $$t)" || { echo "  [FAIL] $$(basename $$t)"; exit 1; }; \
	done

test-build-workflow:
	@echo "==> Running build-level.mjs offline harness..."
	@bash $(BUILD_SRC)/tests/test_workflow.sh

# Glob-based, same rationale as test-board above (F#836): kernel coverage
# can never trail whichever tests/test_*.sh files are actually vendored.
test-conventions-probe:
	@echo "==> Running conventions-probe tests..."
	@for t in $(PROBE_SRC)/tests/test_*.sh; do \
		bash "$$t" >/dev/null 2>&1 && echo "  [ok] $$(basename $$t)" || { echo "  [FAIL] $$(basename $$t)"; exit 1; }; \
	done

# Glob-based, mirroring test-board (F#836) — kernel coverage tracks
# whatever demo tests are actually vendored.
test-demo:
	@echo "==> Running demo-repo seed script tests..."
	@for t in $(DEMO_SRC)/tests/test_*.sh; do \
		bash "$$t" >/dev/null 2>&1 && echo "  [ok] $$(basename $$t)" || { echo "  [FAIL] $$(basename $$t)"; exit 1; }; \
	done

# Glob-based, mirroring test-board (F#836) — kernel coverage tracks whatever
# proposal-pr tests are actually vendored.
test-proposal-pr:
	@echo "==> Running proposal-PR generator tests..."
	@for t in $(PROPOSAL_SRC)/tests/test_*.sh; do \
		bash "$$t" >/dev/null 2>&1 && echo "  [ok] $$(basename $$t)" || { echo "  [FAIL] $$(basename $$t)"; exit 1; }; \
	done

# Glob-based, same rationale as test-board/test-conventions-probe above
# (F#836): kernel coverage can never trail whichever tests/test_*.sh files
# are actually vendored.
test-try:
	@echo "==> Running foundation try tests..."
	@for t in $(BIN_SRC)/subcommands/tests/test_*.sh; do \
		bash "$$t" >/dev/null 2>&1 && echo "  [ok] $$(basename $$t)" || { echo "  [FAIL] $$(basename $$t)"; exit 1; }; \
	done

test-hooks:
	@echo "==> Running hook tests..."
	@for t in $(HOOKS_SRC)/tests/test_*.sh; do \
		bash "$$t" >/dev/null 2>&1 && echo "  [ok] $$(basename $$t)" || { echo "  [FAIL] $$(basename $$t)"; exit 1; }; \
	done

shellcheck:
	@echo "==> shellcheck (production + hook scripts)..."
	@find . -name '*.sh' -not -path './.git/*' -not -path '*/tests/*' -print0 \
		| xargs -0 --no-run-if-empty shellcheck -e SC1091

quality-gates:
	@bash $(FOUNDATION)/scripts/quality-gates.sh

validate-live-drain:
	@bash $(FOUNDATION)/workflows/scripts/validate-live-drain.sh

validate-command-run-emit:
	@bash $(FOUNDATION)/workflows/scripts/validate-command-run-emit.sh

validate-lexicon:
	@bash $(FOUNDATION)/workflows/scripts/drain/validate-lexicon.sh

test-kernel-manifest:
	@echo "==> Running kernel-manifest coverage check..."
	@bash $(FOUNDATION)/workflows/scripts/kernel/check-kernel-manifest.sh

docs:
	@python3 $(FOUNDATION)/workflows/scripts/docs/generate.py

test-docs-generator:
	@echo "==> Running docs generator tests..."
	@python3 -m unittest discover -s $(FOUNDATION)/workflows/scripts/docs/tests -t $(FOUNDATION)/workflows/scripts/docs -v

test-kernel-denylist:
	@echo "==> Running kernel personal-token denylist check..."
	@bash $(FOUNDATION)/workflows/scripts/kernel/check-personal-token-denylist.sh
	@echo "==> Running check-personal-token-denylist.sh fixture tests..."
	@bash $(FOUNDATION)/workflows/scripts/kernel/tests/test_check_personal_token_denylist.sh

test-kernel-gitleaks:
	@echo "==> Running kernel gitleaks scan..."
	@bash $(FOUNDATION)/workflows/scripts/kernel/check-gitleaks-kernel.sh

# Mechanical egress lint over Epic E's before/after value-loop producers
# (foundation #766, privacy/egress audit item): greps the named producer
# scripts for network-call patterns beyond the one sanctioned `gh` channel.
# Standalone-kernel-checkout invocation — no --overlay-report-d, since a
# kernel-only checkout has no .foundation/report.d/ of its own; see this
# repo's own root Makefile for the composed-tree invocation that also
# scans the overlay drop-ins. See check-producer-egress.sh's header for
# the documented (today: empty) opt-in egress surface.
test-producer-egress:
	@echo "==> Running producer egress check..."
	@bash $(FOUNDATION)/workflows/scripts/kernel/check-producer-egress.sh --kernel-root $(FOUNDATION)
	@echo "==> Running check-producer-egress.sh fixture tests..."
	@bash $(FOUNDATION)/workflows/scripts/kernel/tests/test_check_producer_egress.sh

test-scan-stub:
	@echo "==> Running stub scanner tests..."
	@bash $(FOUNDATION)/workflows/scripts/drain/tests/test_scan_stub.sh

lint-pr-body-test:
	@echo "==> Running PR-body issue-linkage lint tests..."
	@bash $(FOUNDATION)/workflows/scripts/tests/test_lint_pr_body.sh

test-install:
	@echo "==> Running install-settings reconcile test..."
	@bash workflows/scripts/tests/test_install_settings.sh

test-install-links:
	@echo "==> Running install-links tests..."
	@bash workflows/scripts/tests/test_install_links.sh

test-install-worktree-guard:
	@echo "==> Running install-worktree-guard tests..."
	@bash workflows/scripts/tests/test_install_worktree_guard.sh

test-prune-branches:
	@echo "==> Running prune-merged-branches tests..."
	@bash scripts/tests/test_prune_merged_branches.sh

test-stranger-config:
	@echo "==> Running stranger-config test..."
	@bash scripts/tests/test_stranger_config.sh
