"""page.py - Page dataclass + a self-contained HTML page shell.

No external fetches: all CSS is inlined into every page (no CDN, no
webfont, no shared asset file to go stale relative to the page that
references it) so any single page is independently viewable.
"""
from __future__ import annotations

import html
from dataclasses import dataclass, field


@dataclass
class Page:
    slug: str          # output path relative to the site root, no extension, e.g. "commands/reference"
    title: str          # nav label + <title>
    body_html: str        # rendered HTML fragment (already escaped/rendered by the caller)
    nav_group: str = "" # optional grouping label for the nav sidebar
    extra: dict = field(default_factory=dict)

    @property
    def output_path(self) -> str:
        return f"{self.slug}.html"


_CSS = """
:root { color-scheme: light dark; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       margin: 0; display: flex; min-height: 100vh; line-height: 1.5; }
nav { flex: 0 0 240px; padding: 1.5rem 1rem; border-right: 1px solid #8884;
      overflow-y: auto; }
nav a { display: block; padding: 0.15rem 0; text-decoration: none; }
nav .group { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;
             opacity: 0.6; margin: 1rem 0 0.25rem; }
main { flex: 1 1 auto; padding: 2rem 2.5rem; max-width: 60rem; }
pre { background: #8882; padding: 0.75rem 1rem; overflow-x: auto; border-radius: 4px; }
code { background: #8882; padding: 0.1rem 0.3rem; border-radius: 3px; }
pre code { background: none; padding: 0; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
th, td { border: 1px solid #8884; padding: 0.4rem 0.6rem; text-align: left; }
footer { margin-top: 3rem; font-size: 0.8rem; opacity: 0.6; }
"""


def render_page(page: Page, nav_items: list[tuple[str, str, str]]) -> str:
    """nav_items: list of (group, href, label) for the sidebar, in display order.

    Deliberately no wall-clock "generated at" timestamp anywhere in the
    output: the acceptance bar requires a re-run on an unchanged tree to be
    byte-identical, and a `datetime.now()` stamp would break that on every
    invocation. The footer names the generator instead of the moment it ran;
    "is this stale" is a question for the CI publish step (a future item) to
    answer via its own build metadata, not something baked into the page.
    """
    groups: dict[str, list[tuple[str, str]]] = {}
    for group, href, label in nav_items:
        groups.setdefault(group, []).append((href, label))

    nav_html = []
    for group, links in groups.items():
        if group:
            nav_html.append(f'<div class="group">{html.escape(group)}</div>')
        for href, label in links:
            nav_html.append(f'<a href="{html.escape(href)}">{html.escape(label)}</a>')

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(page.title)}</title>
<style>{_CSS}</style>
</head>
<body>
<nav>{''.join(nav_html)}</nav>
<main>
<h1>{html.escape(page.title)}</h1>
{page.body_html}
<footer>Generated by workflows/scripts/docs/generate.py — do not edit by hand.</footer>
</main>
</body>
</html>
"""
