#!/usr/bin/env bash
#
# Tests for the compose-plane T0 inventory generated by
# workflows/scripts/install-claude-md.sh (temperloop#235, ADR §2.5 capture
# point 3): the set of knowledge-store notes reachable from the composed
# CLAUDE.md's own rules, written to <dirname target>/t0-inventory.txt on
# every compose. No network, throwaway tmpdir, fixture kernel/overlay docs.
#
# Covers:
#   1. wikilinks + literal (backtick-delimited) store-path references are
#      extracted, alias/anchor suffixes stripped, .md extension stripped
#   2. duplicates across kernel + overlay are deduped
#   3. output is sorted (LC_ALL=C)
#   4. idempotent: second run on the same inputs is byte-identical
#   5. no store references anywhere in either source -> zero-byte file, exit 0
#   6. a non-store `[[...]]`/backtick mention (no Decisions|Patterns|Mistakes|
#      Context prefix) is not picked up
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$(cd "$HERE/.." && pwd)/install-claude-md.sh"

TMP="$(mktemp -d "${TMPDIR:-/tmp}/install-claude-md-t0-test-XXXXXX")"
trap 'rm -rf "$TMP"' EXIT
fail() { echo "FAIL: $1" >&2; exit 1; }

kernel="$TMP/kernel.md"
overlay="$TMP/overlay.md"
target="$TMP/dest/CLAUDE.md"
t0="$TMP/dest/t0-inventory.txt"
mkdir -p "$TMP/dest"

# --- 1-3. wikilinks + literal refs, dedup, sort -------------------------------
cat >"$kernel" <<'EOF'
# Kernel doc
See [[Decisions/foundation - Branch naming convention]] and
[[Patterns/Live-Drain pairing|the pairing pattern]].
Also [[Mistakes/foundation - updateProjectV2Field replaces single-select options#Some anchor]].
Reference: `Context/pipeline - environment hygiene report.md` for details.
A duplicate: [[Decisions/foundation - Branch naming convention]] again.
Not a store note: [[some-other-note]] and `workflows/scripts/foo.md`.
EOF
cat >"$overlay" <<'EOF'
# Overlay doc
Also see [[Context/foundation - pending decisions]] and
`~/knowledge-store/Decisions/foundation - Vault provenance schema (note-level).md`.
Duplicate of a kernel ref: `Context/pipeline - environment hygiene report.md`.
EOF

bash "$SCRIPT" "$kernel" "$overlay" "$target"
[ -f "$t0" ] || fail "1: t0-inventory.txt must be written alongside the composed target"

expected="Context/foundation - pending decisions
Context/pipeline - environment hygiene report
Decisions/foundation - Branch naming convention
Decisions/foundation - Vault provenance schema (note-level)
Mistakes/foundation - updateProjectV2Field replaces single-select options
Patterns/Live-Drain pairing"

actual="$(cat "$t0")"
[ "$actual" = "$expected" ] || fail "1-3: unexpected T0 inventory content
--- expected ---
$expected
--- actual ---
$actual"
echo "PASS: wikilinks + backtick-delimited literal store-path refs extracted, alias/anchor/prefix stripped, deduped, sorted"

# --- 4. idempotent -------------------------------------------------------------
cp "$t0" "$TMP/first.txt"
bash "$SCRIPT" "$kernel" "$overlay" "$target"
diff -q "$TMP/first.txt" "$t0" >/dev/null || fail "4: T0 inventory is not idempotent across identical re-runs"
echo "PASS: T0 inventory regenerates byte-identical on an unchanged re-run"

# --- 5. no store references anywhere -> zero-byte file, no error ---------------
kernel2="$TMP/kernel-empty.md"
overlay2="$TMP/overlay-empty.md"
target2="$TMP/dest2/CLAUDE.md"
t02="$TMP/dest2/t0-inventory.txt"
mkdir -p "$TMP/dest2"
printf '# Plain kernel doc, no store references.\n' >"$kernel2"
printf '# Plain overlay doc, no store references.\n' >"$overlay2"
bash "$SCRIPT" "$kernel2" "$overlay2" "$target2"
[ -f "$t02" ] || fail "5: t0-inventory.txt must still be written when empty"
[ ! -s "$t02" ] || fail "5: t0-inventory.txt must be zero-byte when no store references are present"
echo "PASS: zero store references yields a zero-byte t0-inventory.txt, no error"

# --- 6. non-store wikilink/backtick mentions are excluded -----------------------
! grep -q 'some-other-note' "$t0" || fail "6: a non-store-prefixed wikilink must not appear in the T0 inventory"
! grep -q 'foo' "$t0" || fail "6: a non-store-prefixed backtick path must not appear in the T0 inventory"
echo "PASS: non-store-prefixed wikilinks/backtick paths are excluded from the T0 inventory"

echo "ALL PASS: install-claude-md.sh T0 inventory"
